version: '3'

services:

  nginx: 
    image: nginx
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./html:/etc/nginx/html/
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always